local items = {}
items.spawn =
{
    { price = { { name = 'coin', count = 5 } }, offer = { type = 'give-item', quality = 'legendary', item = 'rail', count = 4 } },
    { price = { { name = 'coin', count = 25 } }, offer = { type = 'give-item', quality = 'legendary', item = 'rail-signal', count = 2 } },
    { price = { { name = 'coin', count = 25 } }, offer = { type = 'give-item', quality = 'legendary', item = 'rail-chain-signal', count = 2 } },
    { price = { { name = 'coin', count = 10 } }, offer = { type = 'give-item', quality = 'legendary', item = 'train-stop' } },
    { price = { { name = 'coin', count = 94 } }, offer = { type = 'give-item', quality = 'legendary', item = 'locomotive' } },
    { price = { { name = 'coin', count = 35 } }, offer = { type = 'give-item', quality = 'legendary', item = 'cargo-wagon' } },
    { price = { { name = 'coin', count = 5 } }, offer = { type = 'give-item', quality = 'legendary', item = 'red-wire', count = 1 } },
    { price = { { name = 'coin', count = 5 } }, offer = { type = 'give-item', quality = 'legendary', item = 'green-wire', count = 1 } },
    { price = { { name = 'coin', count = 4 } }, offer = { type = 'give-item', quality = 'legendary', item = 'decider-combinator' } },
    { price = { { name = 'coin', count = 4 } }, offer = { type = 'give-item', quality = 'legendary', item = 'arithmetic-combinator' } },
    { price = { { name = 'coin', count = 5 } }, offer = { type = 'give-item', quality = 'legendary', item = 'constant-combinator' } },
    { price = { { name = 'coin', count = 7 } }, offer = { type = 'give-item', quality = 'legendary', item = 'programmable-speaker' } },
    { price = { { name = 'coin', count = 5 } }, offer = { type = 'give-item', quality = 'legendary', item = 'small-lamp' } },
    { price = { { name = 'coin', count = 5 } }, offer = { type = 'give-item', quality = 'legendary', item = 'firearm-magazine' } },
    { price = { { name = 'coin', count = 10 } }, offer = { type = 'give-item', quality = 'legendary', item = 'piercing-rounds-magazine' } },
    { price = { { name = 'coin', count = 10 } }, offer = { type = 'give-item', quality = 'legendary', item = 'grenade' } },
    { price = { { name = 'coin', count = 15 } }, offer = { type = 'give-item', quality = 'legendary', item = 'land-mine' } },
    { price = { { name = 'coin', count = 10 } }, offer = { type = 'give-item', quality = 'legendary', item = 'explosives', count = 2 } },
    { price = { { name = 'coin', count = 40 } }, offer = { type = 'give-item', quality = 'legendary', item = 'cliff-explosives' } },
    { price = { { name = 'coin', count = 5 } }, offer = { type = 'give-item', quality = 'legendary', item = 'wood', count = 25 } },
    { price = { { name = 'coin', count = 5 } }, offer = { type = 'give-item', quality = 'legendary', item = 'iron-ore', count = 25 } },
    { price = { { name = 'coin', count = 5 } }, offer = { type = 'give-item', quality = 'legendary', item = 'copper-ore', count = 25 } },
    { price = { { name = 'coin', count = 5 } }, offer = { type = 'give-item', quality = 'legendary', item = 'stone', count = 25 } },
    { price = { { name = 'coin', count = 5 } }, offer = { type = 'give-item', quality = 'legendary', item = 'coal', count = 25 } },
    { price = { { name = 'coin', count = 5 } }, offer = { type = 'give-item', quality = 'legendary', item = 'uranium-ore', count = 20 } },
    { price = { { name = 'wood', count = 25 } }, offer = { type = 'give-item', quality = 'legendary', item = 'raw-fish', count = 2 } },
    { price = { { name = 'iron-ore', count = 25 } }, offer = { type = 'give-item', quality = 'legendary', item = 'raw-fish', count = 2 } },
    { price = { { name = 'copper-ore', count = 25 } }, offer = { type = 'give-item', quality = 'legendary', item = 'raw-fish', count = 2 } },
    { price = { { name = 'stone', count = 25 } }, offer = { type = 'give-item', quality = 'legendary', item = 'raw-fish', count = 2 } },
    { price = { { name = 'coal', count = 25 } }, offer = { type = 'give-item', quality = 'legendary', item = 'raw-fish', count = 2 } },
    { price = { { name = 'uranium-ore', count = 20 } }, offer = { type = 'give-item', quality = 'legendary', item = 'raw-fish', count = 2 } },
    { price = { { name = 'coin', count = 500 } }, offer = { type = 'give-item', quality = 'legendary', item = 'assembling-machine-3' } },
    { price = { { name = 'coin', count = 500 } }, offer = { type = 'give-item', quality = 'legendary', item = 'beacon' } },
    { price = { { name = 'coin', count = 500 } }, offer = { type = 'give-item', quality = 'legendary', item = 'speed-module-3' } },
    { price = { { name = 'coin', count = 500 } }, offer = { type = 'give-item', quality = 'legendary', item = 'productivity-module-3' } },
    { price = { { name = 'coin', count = 500 } }, offer = { type = 'give-item', quality = 'legendary', item = 'efficiency-module-3' } },
    { price = { { name = 'coin', count = 300 } }, offer = { type = 'give-item', quality = 'legendary', item = 'loader', count = 1 } },
    { price = { { name = 'coin', count = 600 } }, offer = { type = 'give-item', quality = 'legendary', item = 'fast-loader', count = 1 } },
    { price = { { name = 'coin', count = 900 } }, offer = { type = 'give-item', quality = 'legendary', item = 'express-loader', count = 1 } },
    { price = { { name = 'coin', count = 45 } }, offer = { type = 'give-item', quality = 'legendary', item = 'logistic-robot', count = 1 } },
    { price = { { name = 'coin', count = 55 } }, offer = { type = 'give-item', quality = 'legendary', item = 'construction-robot', count = 1 } },
    { price = { { name = 'coin', count = 200 } }, offer = { type = 'give-item', quality = 'legendary', item = 'roboport', count = 1 } },
    { price = { { name = 'coin', count = 1000 } }, offer = { type = 'give-item', quality = 'legendary', item = 'car', count = 1 } },
    { price = { { name = 'coin', count = 5000 } }, offer = { type = 'give-item', quality = 'legendary', item = 'tank', count = 1 } },
    { price = { { name = 'coin', count = 10000 } }, offer = { type = 'give-item', quality = 'legendary', item = 'spidertron', count = 1 } },

}
return items
