local waves = {
	{{name = "small-biter", amount = 10}},
	{{name = "small-biter", amount = 20}},
	{{name = "small-biter", amount = 40}},
	{{name = "small-biter", amount = 80}, {name = "small-spitter", amount = 10}},
	{{name = "small-biter", amount = 80}, {name = "small-spitter", amount = 20}},
	{{name = "small-biter", amount = 80}, {name = "small-spitter", amount = 40}},
	{{name = "medium-biter", amount = 1}, {name = "small-biter", amount = 80}, {name = "small-spitter", amount = 80}},
	{{name = "medium-biter", amount = 10}, {name = "small-spitter", amount = 80}},
	{{name = "medium-biter", amount = 20}, {name = "small-spitter", amount = 80}},
	{{name = "medium-biter", amount = 40}, {name = "small-spitter", amount = 80}},
	{{name = "medium-biter", amount = 80}, {name = "small-spitter", amount = 80}},
	{{name = "medium-biter", amount = 80}, {name = "medium-spitter", amount = 10}},
	{{name = "medium-biter", amount = 80}, {name = "medium-spitter", amount = 20}},
	{{name = "medium-biter", amount = 80}, {name = "medium-spitter", amount = 40}},
	{{name = "big-biter", amount = 1},{name = "medium-biter", amount = 80}, {name = "medium-spitter", amount = 80}},
	{{name = "big-biter", amount = 10}, {name = "medium-spitter", amount = 80}},
	{{name = "big-biter", amount = 20}, {name = "medium-spitter", amount = 80}},
	{{name = "big-biter", amount = 40}, {name = "medium-spitter", amount = 80}},
	{{name = "big-biter", amount = 80}, {name = "medium-spitter", amount = 80}},
	{{name = "big-biter", amount = 80}, {name = "big-spitter", amount = 10}},
	{{name = "big-biter", amount = 80}, {name = "big-spitter", amount = 20}},
	{{name = "big-biter", amount = 80}, {name = "big-spitter", amount = 40}},
	{{name = "behemoth-biter", amount = 1},{name = "big-biter", amount = 80}, {name = "big-spitter", amount = 80}},
	{{name = "behemoth-biter", amount = 10}, {name = "big-spitter", amount = 80}},
	{{name = "behemoth-biter", amount = 20}, {name = "big-spitter", amount = 80}},
	{{name = "behemoth-biter", amount = 40}, {name = "big-spitter", amount = 80}},
	{{name = "behemoth-biter", amount = 80}, {name = "big-spitter", amount = 80}},
	{{name = "behemoth-biter", amount = 80}, {name = "behemoth-spitter", amount = 10}},
	{{name = "behemoth-biter", amount = 80}, {name = "behemoth-spitter", amount = 20}},
	{{name = "behemoth-biter", amount = 80}, {name = "behemoth-spitter", amount = 40}},
	{{name = "behemoth-biter", amount = 80}, {name = "behemoth-spitter", amount = 60}},
	{{name = "behemoth-biter", amount = 100}, {name = "behemoth-spitter", amount = 70}},
	{{name = "behemoth-biter", amount = 125}, {name = "behemoth-spitter", amount = 80}},
	{{name = "behemoth-biter", amount = 150}, {name = "behemoth-spitter", amount = 90}},
	{{name = "behemoth-biter", amount = 175}, {name = "behemoth-spitter", amount = 95}},
	{{name = "behemoth-biter", amount = 200}, {name = "behemoth-spitter", amount = 100}},
	{{name = "behemoth-biter", amount = 225}, {name = "behemoth-spitter", amount = 110}},
	{{name = "behemoth-biter", amount = 250}, {name = "behemoth-spitter", amount = 125}},
	{{name = "behemoth-biter", amount = 275}, {name = "behemoth-spitter", amount = 135}},
	{{name = "behemoth-biter", amount = 300}, {name = "behemoth-spitter", amount = 150}}
}

return waves
