local waves = {
	[1] = {{name = "small-biter", amount = 10}},
	[2] = {{name = "small-biter", amount = 20}},
	[3] = {{name = "small-biter", amount = 40}},
	[4] = {{name = "small-biter", amount = 80}, {name = "small-spitter", amount = 10}},
	[5] = {{name = "small-biter", amount = 80}, {name = "small-spitter", amount = 20}},
	[6] = {{name = "small-biter", amount = 80}, {name = "small-spitter", amount = 40}},
	[7] = {{name = "small-biter", amount = 80}, {name = "small-spitter", amount = 80}},
	[8] = {{name = "medium-biter", amount = 10}, {name = "small-spitter", amount = 80}},
	[9] = {{name = "medium-biter", amount = 20}, {name = "small-spitter", amount = 80}},
	[10] = {{name = "medium-biter", amount = 40}, {name = "small-spitter", amount = 80}},
	[11] = {{name = "medium-biter", amount = 80}, {name = "small-spitter", amount = 80}},
	[12] = {{name = "medium-biter", amount = 80}, {name = "medium-spitter", amount = 10}},
	[13] = {{name = "medium-biter", amount = 80}, {name = "medium-spitter", amount = 20}},
	[14] = {{name = "medium-biter", amount = 80}, {name = "medium-spitter", amount = 40}},
	[15] = {{name = "medium-biter", amount = 80}, {name = "medium-spitter", amount = 80}},
	[16] = {{name = "big-biter", amount = 10}, {name = "medium-spitter", amount = 80}},
	[17] = {{name = "big-biter", amount = 20}, {name = "medium-spitter", amount = 80}},
	[18] = {{name = "big-biter", amount = 40}, {name = "medium-spitter", amount = 80}},
	[19] = {{name = "big-biter", amount = 80}, {name = "medium-spitter", amount = 80}},
	[20] = {{name = "big-biter", amount = 80}, {name = "big-spitter", amount = 10}},
	[21] = {{name = "big-biter", amount = 80}, {name = "big-spitter", amount = 20}},
	[22] = {{name = "big-biter", amount = 80}, {name = "big-spitter", amount = 40}},
	[23] = {{name = "big-biter", amount = 80}, {name = "big-spitter", amount = 80}},
	[24] = {{name = "behemoth-biter", amount = 10}, {name = "big-spitter", amount = 80}},
	[25] = {{name = "behemoth-biter", amount = 20}, {name = "big-spitter", amount = 80}},
	[26] = {{name = "behemoth-biter", amount = 40}, {name = "big-spitter", amount = 80}},
	[27] = {{name = "behemoth-biter", amount = 80}, {name = "big-spitter", amount = 80}},
	[28] = {{name = "behemoth-biter", amount = 80}, {name = "behemoth-spitter", amount = 10}},
	[29] = {{name = "behemoth-biter", amount = 80}, {name = "behemoth-spitter", amount = 20}},
	[30] = {{name = "behemoth-biter", amount = 80}, {name = "behemoth-spitter", amount = 40}},
	[31] = {{name = "behemoth-biter", amount = 80}, {name = "behemoth-spitter", amount = 80}}
}

return waves
