local Public = require 'maps.mountain_fortress_v3.table'

Public.stateful = require 'maps.mountain_fortress_v3.stateful.main'
Public.balance = require 'maps.mountain_fortress_v3.balance'
Public.basic_markets = require 'maps.mountain_fortress_v3.basic_markets'
Public.biters_yield_coins = require 'maps.mountain_fortress_v3.biters_yield_coins'
Public.breached_wall = require 'maps.mountain_fortress_v3.breached_wall'
Public.buried_enemies = require 'maps.mountain_fortress_v3.buried_enemies'
Public.commands = require 'maps.mountain_fortress_v3.commands'
Public.entities = require 'maps.mountain_fortress_v3.entities'
Public.functions = require 'maps.mountain_fortress_v3.functions'
Public.terrain = require 'maps.mountain_fortress_v3.terrain'
Public.generate = require 'maps.mountain_fortress_v3.generate'
Public.get_perlin = require 'maps.mountain_fortress_v3.get_perlin'
Public.gui = require 'maps.mountain_fortress_v3.gui'
-- Public.highscore = require 'maps.mountain_fortress_v3.highscore'
Public.locomotive = require 'maps.mountain_fortress_v3.locomotive'
Public.loot = require 'maps.mountain_fortress_v3.loot'
Public.mining = require 'maps.mountain_fortress_v3.mining'
Public.mystical_chest = require 'maps.mountain_fortress_v3.mystical_chest'
Public.resource_generator = require 'maps.mountain_fortress_v3.resource_generator'
Public.rocks_yield_ore_veins = require 'maps.mountain_fortress_v3.rocks_yield_ore_veins'
Public.soft_reset = require 'maps.mountain_fortress_v3.soft_reset'
Public.surface = require 'maps.mountain_fortress_v3.surface'
Public.traps = require 'maps.mountain_fortress_v3.traps'
Public.defense_system = require 'maps.mountain_fortress_v3.locomotive.defense_system'
Public.friendly_pet = require 'maps.mountain_fortress_v3.locomotive.friendly_pet'
Public.market = require 'maps.mountain_fortress_v3.locomotive.market'
Public.permission_groups = require 'maps.mountain_fortress_v3.locomotive.permission_groups'
Public.spawn_locomotive = require 'maps.mountain_fortress_v3.locomotive.spawn_locomotive'
Public.charging_station = require 'maps.mountain_fortress_v3.charging_station'

return Public
